module ACH
  module Constants
    RECORD_SIZE     = 94
    BLOCKING_FACTOR = 10
    FORMAT_CODE     = 1
    ROWS_DELIMITER  = "\n"

    FILE_HEADER_RECORD_TYPE   = 1
    FILE_CONTROL_RECORD_TYPE  = 9
    BATCH_HEADER_RECORD_TYPE  = 5
    BATCH_ENTRY_RECORD_TYPE   = 6
    BATCH_ADDENDA_RECORD_TYPE = 7
    BATCH_CONTROL_RECORD_TYPE = 8
  end
end